name: "Github Action Packer"

on:
  push:
    branches:
      - master

jobs:


  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_ID}}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION}}
      PACKER_VERSION: "1.9.4"

    steps:
      - name: "Repository Checkoout"
        uses: actions/checkout@v3

      - name: "Setup packer"
        uses: hashicorp/setup-packer@main
        with:
           version: ${{ env.PACKER_VERSION }}

      - name: "packer init"
        run: packer init .
        working-directory: ./packer/

      - name: "Packer validate"
        run: packer validate ./packer/
  
      - name: "Packer build image"
        run: packer build .
        working-directory: ./packer/

      - name: "List Current working directory"
        run: |
          pwd
          ls -al
